version: '3.9'
services:

  spring-api:
    image: dockerizado-spring-api
    build: .
    container_name: spring-api-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
      image: postgres:latest
      restart: always
      container_name: my-postgres-container
      environment:
        POSTGRES_DB: DB_Productos
        POSTGRES_USER: soporte
        POSTGRES_PASSWORD: soporte
        PGDATA: /var/lib/postgresql/data
      volumes:
        - ./data:/var/lib/postgresql/data
      ports:
        - '5433:5432'

  pgadmin4:
      image: dpage/pgadmin4:latest
      restart: always
      container_name: my-pgadmin4-container
      environment:
        PGADMIN_DEFAULT_EMAIL: byschoo@outlook.com
        PGADMIN_DEFAULT_PASSWORD: byschoo
        PGADMIN_LISTEN_PORT: 8080
      ports:
        - "8090:8080"
      volumes:
        - ./servers.json:/pgadmin4/servers.json
