version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    container_name: db_postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./postgres:/var/lib/postgresql/data
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports:
      - "5432:5432"

  web:
    image: adminer
    restart: always
    container_name: web_adminer
    # 8081 evita interferencia con el puerto 8080 configurado en el application.properties
    ports:
      - 8081:8080